language: c
git:
  depth: 1
addons:
  apt:
    update: false
    packages:
    - clang-format
    - colordiff
script:
 - .scripts/travis/test_all.sh
matrix:
  include:
    - os: linux
      name: "Some GNU/Linux"
    - os: osx
      name: "macOS"
