language: generic
git:
  depth: 1
#addons:
#  apt:
#    update: false
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#      - gcc
#      - coreutils
#      - diffutils
#    - binutils
#    - gcc-6
#    - colordiff
install:
 - .scripts/travis/install.sh
script:
  - gcc --version
  - .scripts/travis/test_all.sh
matrix:
  include:
    - os: linux
      name: "Some GNU/Linux (Light checks)"
    - os: linux
      name: "Xenial GCC 8 sanitized"
      env: CC=gcc-8 TEST_SANITIZE_MODE=gcc-8-mpx
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - gcc-8

    - os: osx
      name: "macOS"
